version: "3.9"
services:
  metric-app:
    build: ./
    ports:
      - "8080:8080"
    entrypoint:
      - /bin/metric-simulator
      - --mc=7   # Chnage this value for number of random metrics
      - --ac=EDGE-1 # Change this value making the tenant
  vm:
    image: "victoriametrics/victoria-metrics"
    ports:
      - "8428:8428"
    volumes:
      - ./victoria-metrics-data :/victoria-metrics-data       
  prometheus:
    image: "prom/prometheus"
    volumes:
        - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"  
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"  
    volumes: 
      - ./grafana/provisioning/:/etc/grafana/provisioning/
          


